package PanelesTexto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.Font;

/**
 * Es un panel de texto muestra el texto recibido, no admite HTML
 * @author Nacho
 */
public class PanelPaginaDeTexto extends javax.swing.JPanel {

    /**
     * Creates new form PanelPaginaTexto
     */
    public PanelPaginaDeTexto() {
        initComponents();
    }

    public PanelPaginaDeTexto(String titulo,String texto) {

        initComponents();
        this.titulo.setText(titulo);
        this.cuadroTexto.setText(texto);
        this.cuadroTexto.setEditable(false);
    }
    public PanelPaginaDeTexto(String titulo,String texto,Boolean editable) {
        initComponents();
        this.titulo.setText(titulo);
        this.cuadroTexto.setText(texto);
        this.cuadroTexto.setEditable(editable);
    }
    public PanelPaginaDeTexto(String titulo, String texto, Font fuenteTitulo, Font fuenteTexto, Boolean editable) {
        initComponents();
        
        this.titulo.setText(titulo);
        this.cuadroTexto.setText(texto);
        this.cuadroTexto.setEditable(editable);
        this.titulo.setFont(fuenteTitulo);
        this.cuadroTexto.setFont(fuenteTexto);
    }
    public PanelPaginaDeTexto(String titulo, String texto, Font fuenteTitulo, Font fuenteTexto) {
        initComponents();

        this.titulo.setText(titulo);
        this.cuadroTexto.setText(texto);
        this.cuadroTexto.setEditable(false);
        this.titulo.setFont(fuenteTitulo);
        this.cuadroTexto.setFont(fuenteTexto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroTexto = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setText("Titulo");
        jPanel1.add(titulo);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        cuadroTexto.setColumns(20);
        cuadroTexto.setRows(5);
        jScrollPane1.setViewportView(cuadroTexto);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cuadroTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
