/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import data.App;
import javax.swing.JOptionPane;

/**
 *
 * @author Nacho
 */
public class VentanaJuego extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    App a;
    String cadManoJugador;
    
    public VentanaJuego(App a) {
        initComponents();
        this.a = a;
        inicializarPartida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        ListaDePuntos = new javax.swing.JPanel();
        tituloPuntos = new javax.swing.JLabel();
        puntosDos = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();
        puntosAS = new javax.swing.JLabel();
        puntosTres = new javax.swing.JLabel();
        puntosCaballo = new javax.swing.JLabel();
        puntosSota = new javax.swing.JLabel();
        puntosRey = new javax.swing.JLabel();
        tituloTurnoDelJugador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        verMano = new javax.swing.JTextArea();
        botonPlantarse = new javax.swing.JButton();
        botonRobarCarta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(104, 62, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaDePuntos.setBackground(new java.awt.Color(255, 204, 153));
        ListaDePuntos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0)));
        ListaDePuntos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ListaDePuntos.setLayout(new java.awt.GridBagLayout());

        tituloPuntos.setForeground(new java.awt.Color(0, 0, 0));
        tituloPuntos.setText("Puntos:");
        ListaDePuntos.add(tituloPuntos, new java.awt.GridBagConstraints());

        puntosDos.setForeground(new java.awt.Color(0, 0, 0));
        puntosDos.setText("DOS: 2 puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        ListaDePuntos.add(puntosDos, gridBagConstraints);

        barra.setForeground(new java.awt.Color(0, 0, 0));
        barra.setText("__________________");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        ListaDePuntos.add(barra, gridBagConstraints);

        puntosAS.setForeground(new java.awt.Color(0, 0, 0));
        puntosAS.setText("AS: 1 punto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        ListaDePuntos.add(puntosAS, gridBagConstraints);

        puntosTres.setForeground(new java.awt.Color(0, 0, 0));
        puntosTres.setText("TRES: 3 puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        ListaDePuntos.add(puntosTres, gridBagConstraints);

        puntosCaballo.setForeground(new java.awt.Color(0, 0, 0));
        puntosCaballo.setText("CABALLO: 0,5 puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        ListaDePuntos.add(puntosCaballo, gridBagConstraints);

        puntosSota.setForeground(new java.awt.Color(0, 0, 0));
        puntosSota.setText("SOTA: 0,5 puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        ListaDePuntos.add(puntosSota, gridBagConstraints);

        puntosRey.setForeground(new java.awt.Color(0, 0, 0));
        puntosRey.setText("REY: 0,5 puntos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        ListaDePuntos.add(puntosRey, gridBagConstraints);

        jPanel2.add(ListaDePuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 130, 170));

        tituloTurnoDelJugador.setBackground(new java.awt.Color(255, 255, 255));
        tituloTurnoDelJugador.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        tituloTurnoDelJugador.setForeground(new java.awt.Color(0, 0, 0));
        tituloTurnoDelJugador.setText("Turno de cambiame");
        jPanel2.add(tituloTurnoDelJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 460, 59));

        verMano.setColumns(20);
        verMano.setRows(5);
        verMano.setText("Cartas en la mano del jugador:");
        jScrollPane1.setViewportView(verMano);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 710, 180));

        botonPlantarse.setText("Plantarse");
        botonPlantarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlantarseActionPerformed(evt);
            }
        });
        jPanel2.add(botonPlantarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        botonRobarCarta.setText("Robar Carta");
        botonRobarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRobarCartaActionPerformed(evt);
            }
        });
        jPanel2.add(botonRobarCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPlantarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlantarseActionPerformed
        // TODO add your handling code here:
        a.getJ().setPlantado(true);
        JOptionPane.showMessageDialog(null, "Se ha plantado "+ a.getJ()+" con una cantidad de puntos de "
                                        + a.getJ().sumarPuntos());
        
        if (a.getJ1().isPlantado() && a.getJ2().isPlantado()){
        JOptionPane.showMessageDialog(null,"La partida ha finalizado");
        this.setVisible(false);
        
        VentanaResultados v = new VentanaResultados(a);
        v.setVisible(true);
        v.setResizable(false);
        v.setLocationRelativeTo(null);
        v.setSize(703, 454);
        
        this.dispose();
        }
        else
        cambiarTurno();
    }//GEN-LAST:event_botonPlantarseActionPerformed

    private void botonRobarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRobarCartaActionPerformed
        // TODO add your handling code here:
        a.getJ().robarCarta(a.getBaraja());
        
        JOptionPane.showMessageDialog(null,"Has robado la siguiente carta: "+a.getJ().getManoJugador().getLast());
        
        
        inicializarTurno();
        
    }//GEN-LAST:event_botonRobarCartaActionPerformed

    private void cambiarTurno(){
        
        a.setEsTurnoDeJug1(! a.GetEsTurnoJ1());
        
        inicializarTurno();
    }
    
    
    private void inicializarTurno(){
        
        
        cadManoJugador="Cartas en la mano de "+ a.getJ().getNombre() +": \n ______________________ \n";
        tituloTurnoDelJugador.setText("Turno de "+ a.getJ().getNombre());
        verMano.setText(cadManoJugador + a.getJ().verMano());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListaDePuntos;
    private javax.swing.JLabel barra;
    private javax.swing.JButton botonPlantarse;
    private javax.swing.JButton botonRobarCarta;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel puntosAS;
    private javax.swing.JLabel puntosCaballo;
    private javax.swing.JLabel puntosDos;
    private javax.swing.JLabel puntosRey;
    private javax.swing.JLabel puntosSota;
    private javax.swing.JLabel puntosTres;
    private javax.swing.JLabel tituloPuntos;
    private javax.swing.JLabel tituloTurnoDelJugador;
    private javax.swing.JTextArea verMano;
    // End of variables declaration//GEN-END:variables

    private void inicializarPartida() {
        
        a.setEsTurnoDeJug1(a.empezarJuego());
        a.rellenarBaraja();
        a.getJ1().getManoJugador().clear();
        a.getJ2().getManoJugador().clear();
        a.getJ1().setPlantado(false);
        a.getJ2().setPlantado(false);
        inicializarTurno();    
    }
}
