/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Nacho
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuGerente
     */
    Vpp v;

    
    public PanelPrincipal(Vpp v) {
        this.v=v;      
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        bItalia = new javax.swing.JButton();
        bFrancia = new javax.swing.JButton();
        bEsp = new javax.swing.JButton();
        bAlemania = new javax.swing.JButton();
        BCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nombreGerente = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 142, 7));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 150, 20, 150));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        bItalia.setText("Torneo de Italia");
        bItalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bItaliaActionPerformed(evt);
            }
        });
        jPanel1.add(bItalia);

        bFrancia.setText("Torneo de Francia");
        bFrancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFranciaActionPerformed(evt);
            }
        });
        jPanel1.add(bFrancia);

        bEsp.setText("Torneo de España");
        bEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEspActionPerformed(evt);
            }
        });
        jPanel1.add(bEsp);

        bAlemania.setText("Torneo de Alemania");
        bAlemania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlemaniaActionPerformed(evt);
            }
        });
        jPanel1.add(bAlemania);

        BCerrar.setText("Cerrar Aplicacion");
        BCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(BCerrar);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        nombreGerente.setFont(new java.awt.Font("FOT-Cezanne Pro B", 1, 18)); // NOI18N
        nombreGerente.setForeground(new java.awt.Color(255, 255, 255));
        nombreGerente.setText("Bienvenido a Tenis DAM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 119, 29, 95);
        jPanel2.add(nombreGerente, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void BCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarActionPerformed

    }//GEN-LAST:event_BCerrarActionPerformed

    private void bFranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFranciaActionPerformed

    }//GEN-LAST:event_bFranciaActionPerformed

    private void bItaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bItaliaActionPerformed

    }//GEN-LAST:event_bItaliaActionPerformed

    private void bEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEspActionPerformed

    }//GEN-LAST:event_bEspActionPerformed

    private void bAlemaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlemaniaActionPerformed

    }//GEN-LAST:event_bAlemaniaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCerrar;
    private javax.swing.JButton bAlemania;
    private javax.swing.JButton bEsp;
    private javax.swing.JButton bFrancia;
    private javax.swing.JButton bItalia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreGerente;
    // End of variables declaration//GEN-END:variables
}
