/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JFrame;

/**
 *
 * @author Nacho
 */
public class PanelP extends javax.swing.JPanel {

    /**
     * Creates new form PanelP
     */
    
    MiVentana v;
            
    public PanelP(MiVentana v) {
        this.v=v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b_1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);

        b_1.setText("-1");
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });
        jPanel1.add(b_1);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);

        b_2.setText("-2");
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });
        jPanel1.add(b_2);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);

        b_3.setText("-3");
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });
        jPanel1.add(b_3);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText(" ");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("                 ");
        add(jLabel2, java.awt.BorderLayout.LINE_END);

        jLabel3.setText("                 ");
        add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel4.setText("                 ");
        add(jLabel4, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    V1 v1;
    V2 v2;
    V3 v3;
    
    
    
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(v1==null){
            v1=new V1();
            v1.setVisible(true);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(v2==null){
            v2=new V2();
            v2.setVisible(true);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
        if(v3==null){
            v3=new V3();
            v3.setVisible(true);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
        // TODO add your handling code here:
       if(v1!=null){
            v1.dispose();
            v1=null;
        }
    }//GEN-LAST:event_b_1ActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
        // TODO add your handling code here:
        if(v2!=null){
            v2.dispose();
            v2=null;
        }
    }//GEN-LAST:event_b_2ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
        // TODO add your handling code here:
        if(v3!=null){
            v3.dispose();
            v3=null;
        }
    }//GEN-LAST:event_b_3ActionPerformed
                                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
