/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import data.Articulo;
import data.Gerente;
import data.Marcas;
import data.PersonalTienda;
import data.Prendas;
import data.Tienda;
import data.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author grovy
 */
public class PanelAgregarArticulos extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuGerente
     */
    VentanaPrincipal v;
    Tienda t;
    Gerente pt;
    
    public PanelAgregarArticulos(VentanaPrincipal v, Tienda t, PersonalTienda pt) {
        this.t=t;
        this.v=v;
        this.pt=(Gerente)pt;
        //v.setSize(600, 60);
        //v.setLocationRelativeTo(null);
        
        initComponents();
        
        nombreGerente.setText("Bienvenido a "+ t.getNombre()+", "+pt.getNombreCompleto());
        
        agregarEnumsAlComboBox(Marcas.values(),cbMarca);
        agregarEnumsAlComboBox(Prendas.values(),cbPrenda);
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bAgregarArticulo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPrenda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbMarca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nombreGerente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bVolverAtras = new javax.swing.JButton();
        bVolverMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));
        setLayout(new java.awt.BorderLayout());

        jLabel3.setText("                               ");
        add(jLabel3, java.awt.BorderLayout.LINE_START);

        jLabel4.setText("                               ");
        add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setOpaque(false);

        bAgregarArticulo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        bAgregarArticulo.setText("Agregar Articulo");
        bAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarArticuloActionPerformed(evt);
            }
        });
        jPanel5.add(bAgregarArticulo);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 51, 51)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0))));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel8.setText(" ");
        jPanel4.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(80, 1, 80, 1));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(0, 2, 10, 30));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo de prenda");
        jPanel6.add(jLabel1);

        cbPrenda.setBackground(new java.awt.Color(154, 219, 219));
        cbPrenda.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        cbPrenda.setForeground(new java.awt.Color(0, 0, 0));
        cbPrenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrendaActionPerformed(evt);
            }
        });
        jPanel6.add(cbPrenda);

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Marca");
        jPanel6.add(jLabel2);

        cbMarca.setBackground(new java.awt.Color(154, 219, 219));
        cbMarca.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        cbMarca.setForeground(new java.awt.Color(0, 0, 0));
        cbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(cbMarca);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Modelo (opcional)");
        jPanel6.add(jLabel6);

        tModelo.setBackground(new java.awt.Color(154, 219, 219));
        tModelo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        tModelo.setForeground(new java.awt.Color(0, 0, 0));
        tModelo.setToolTipText("Elige el nombre que tendra el modelo");
        jPanel6.add(tModelo);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jLabel10.setText("   ");
        jPanel4.add(jLabel10, java.awt.BorderLayout.LINE_END);

        jLabel11.setText(" ");
        jPanel4.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        nombreGerente.setFont(new java.awt.Font("FOT-Cezanne Pro B", 1, 18)); // NOI18N
        nombreGerente.setForeground(new java.awt.Color(255, 255, 255));
        nombreGerente.setText("Bienvenido \"Nombre Empleado\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 119, 29, 95);
        jPanel2.add(nombreGerente, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        bVolverAtras.setText("Volver Atras");
        bVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverAtrasActionPerformed(evt);
            }
        });
        jPanel3.add(bVolverAtras);

        bVolverMenu.setText("Volver al Menu");
        bVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverMenuActionPerformed(evt);
            }
        });
        jPanel3.add(bVolverMenu);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverMenuActionPerformed
        // TODO add your handling code here:
        //esto vuelve al menu principal
        if(pt.getClass()==Gerente.class)
            this.v.ponPanel(Paneles.PMenuGerente, pt);
        
            
    }//GEN-LAST:event_bVolverMenuActionPerformed

    private void bVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverAtrasActionPerformed
        // TODO add your handling code here:
        if(pt.getClass()==Gerente.class)
            this.v.ponPanel(Paneles.PGestionarArticulos, pt);
    }//GEN-LAST:event_bVolverAtrasActionPerformed

    private void bAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarArticuloActionPerformed
        // genero un articulos con los datos dados por el usuario
        Marcas marca = null;
        //guardo la marca que he seleccionado
        for (int i = 0; i < Marcas.values().length; i++) {
            if(cbMarca.getSelectedItem()==Marcas.values()[i].name())
                marca=Marcas.values()[i];
        }
        Prendas prenda= null;
        //guardo la prenda que he seleccionado
        for (int i = 0; i < Prendas.values().length; i++) {
            if(cbPrenda.getSelectedItem()==Prendas.values()[i].name())
                prenda=Prendas.values()[i];
        }
        
        String modelo=tModelo.getText();
        
        Gerente g= (Gerente) pt;
        Articulo articulo;
       //si la longitud del modelo es menor que 3, se crea con un modelo basico, si no con el que se le de
        if (modelo.length()<3)
            articulo = new Articulo(prenda,marca);
        else
            articulo = new Articulo(prenda,marca,modelo);
        
        t.getArticulosTienda().add(articulo);
        
        JOptionPane.showMessageDialog(this, "Articulo agregado con exito");
        
        
    }//GEN-LAST:event_bAgregarArticuloActionPerformed

    private void cbPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrendaActionPerformed

   
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Image fondo = null;
        try {
            fondo = ImageIO.read(new File("src/IMG/fondoMenus.jpg")); //esto lo he tenido que buscar en internet
        } catch (IOException ex) {
            Logger.getLogger(PanelLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image fondoEscalado = fondo.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        
        g.drawImage(fondoEscalado, 0, 0, this);
        this.repaint();
        this.revalidate();
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarArticulo;
    private javax.swing.JButton bVolverAtras;
    private javax.swing.JButton bVolverMenu;
    private javax.swing.JComboBox<String> cbMarca;
    private javax.swing.JComboBox<String> cbPrenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nombreGerente;
    private javax.swing.JTextField tModelo;
    // End of variables declaration//GEN-END:variables

    private void agregarEnumsAlComboBox(Enum[] values, JComboBox<String> comboBox) {
        
        comboBox.removeAllItems();
        
        //Convierto el array de enumerados con todos los valores, las paso a un array de Strings, y las añado

        String[] lista = new String[values.length];
       
        for (int i = 0; i < values.length; i++) {
            lista[i]=values[i].name();
            comboBox.addItem(lista[i]);
        }
        
    }
}
