/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import data.Gerente;
import data.Marcas;
import data.PersonalTienda;
import data.Tienda;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author grovy
 */
public class PanelMostrarEjemplaresPorMarca extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuGerente
     */
    VentanaPrincipal v;
    Tienda t;
    PersonalTienda pt;
    
    PanelMostrarEjemplaresPorMarca(VentanaPrincipal v, Tienda t, PersonalTienda pt) {
        this.t=t;
        this.v=v;
        this.pt=pt;
        //v.setSize(600, 600);
        //v.setLocationRelativeTo(null);
        
        initComponents();
        
        
        nombreGerente.setText("Bienvenido a "+ t.getNombre()+", "+pt.getNombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        bPulga = new javax.swing.JButton();
        bAdidos = new javax.swing.JButton();
        bKike = new javax.swing.JButton();
        bSuprememe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nombreGerente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bVolverAtras = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 75, 50, 75));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 20, 20));

        bPulga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPulgaActionPerformed(evt);
            }
        });
        jPanel1.add(bPulga);

        bAdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdidosActionPerformed(evt);
            }
        });
        jPanel1.add(bAdidos);

        bKike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKikeActionPerformed(evt);
            }
        });
        jPanel1.add(bKike);

        bSuprememe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuprememeActionPerformed(evt);
            }
        });
        jPanel1.add(bSuprememe);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        nombreGerente.setFont(new java.awt.Font("FOT-Cezanne Pro B", 1, 18)); // NOI18N
        nombreGerente.setForeground(new java.awt.Color(255, 255, 255));
        nombreGerente.setText("Bienvenido \"Nombre Empleado\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 119, 29, 95);
        jPanel2.add(nombreGerente, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        bVolverAtras.setText("Volver atras");
        bVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverAtrasActionPerformed(evt);
            }
        });
        jPanel3.add(bVolverAtras);

        bVolver.setText("Volver al menu");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });
        jPanel3.add(bVolver);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        //esto vuelve al menu principal
        if(pt.getClass()==Gerente.class)
            this.v.ponPanel(Paneles.PMenuGerente, pt);
        
            
    }//GEN-LAST:event_bVolverActionPerformed

    private void bKikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKikeActionPerformed
        // TODO add your handling code here:
        this.v.ponPanelMostrarLista(Paneles.PMostrarListas, pt, Paneles.PMostrarEjemplaresPorMarca,
                pt.mostrarEjemMarca(Marcas.Kike, t.getArticulosTienda()));
        
    }//GEN-LAST:event_bKikeActionPerformed

    private void bPulgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPulgaActionPerformed
        // TODO add your handling code here:
                this.v.ponPanelMostrarLista(Paneles.PMostrarListas, pt, Paneles.PMostrarEjemplaresPorMarca,
                pt.mostrarEjemMarca(Marcas.Pulga, t.getArticulosTienda()));

    }//GEN-LAST:event_bPulgaActionPerformed

    private void bAdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdidosActionPerformed
        // TODO add your handling code here:
                this.v.ponPanelMostrarLista(Paneles.PMostrarListas, pt, Paneles.PMostrarEjemplaresPorMarca,
                pt.mostrarEjemMarca(Marcas.Adidos, t.getArticulosTienda()));

    }//GEN-LAST:event_bAdidosActionPerformed

    private void bSuprememeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuprememeActionPerformed
        // TODO add your handling code here:
                this.v.ponPanelMostrarLista(Paneles.PMostrarListas, pt, Paneles.PMostrarEjemplaresPorMarca,
                pt.mostrarEjemMarca(Marcas.Suprememe, t.getArticulosTienda()));

    }//GEN-LAST:event_bSuprememeActionPerformed

    private void bVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverAtrasActionPerformed
        // TODO add your handling code here:
        this.v.ponPanel(Paneles.PMostrarEjemplares, pt);
    }//GEN-LAST:event_bVolverAtrasActionPerformed

   
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Image fondo = null;
        try {
            fondo = ImageIO.read(new File("src/IMG/fondoMenus.jpg")); //esto lo he tenido que buscar en internet
        } catch (IOException ex) {
            Logger.getLogger(PanelLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image fondoEscalado = fondo.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        
        g.drawImage(fondoEscalado, 0, 0, this);
        
        
        pintarBotones();
        
        //this.repaint();
        //this.revalidate();
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdidos;
    private javax.swing.JButton bKike;
    private javax.swing.JButton bPulga;
    private javax.swing.JButton bSuprememe;
    private javax.swing.JButton bVolver;
    private javax.swing.JButton bVolverAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombreGerente;
    // End of variables declaration//GEN-END:variables

   
    private void pintarBotones() {
        //@Nacho
        //esto pinta los logos en los botones
        
        //aqui no entiendo por que no puedo recibir la anchura y altura de boton, me dan un error que dice que valen 0
        
        ImageIcon logoAdidos = new ImageIcon("src/IMG/Logo_adidos.png"); //creamos un icono de imagen a partir de la imagen seleccionada
        bAdidos.setIcon(new ImageIcon(logoAdidos.getImage().getScaledInstance
        (bAdidos.getWidth(), bAdidos.getHeight(), Image.SCALE_SMOOTH))); 
    
        ImageIcon logoPulga = new ImageIcon("src/IMG/Logo_Pulga.png"); //creamos un icono de imagen a partir de la imagen seleccionada
        bPulga.setIcon(new ImageIcon(logoPulga.getImage().getScaledInstance
        (bPulga.getWidth(), bPulga.getHeight(), Image.SCALE_SMOOTH))); 
    
        ImageIcon logoSuprememe = new ImageIcon("src/IMG/Logo_Suprememe.png"); //creamos un icono de imagen a partir de la imagen seleccionada
        bSuprememe.setIcon(new ImageIcon(logoSuprememe.getImage().getScaledInstance
        (bSuprememe.getWidth(), bSuprememe.getHeight(), Image.SCALE_SMOOTH))); 
    
        ImageIcon logoKike = new ImageIcon("src/IMG/Logo_Kike.png"); //creamos un icono de imagen a partir de la imagen seleccionada
        bKike.setIcon(new ImageIcon(logoKike.getImage().getScaledInstance
        (bKike.getWidth(), bKike.getHeight(), Image.SCALE_SMOOTH))); 
    
                
       }

}
