/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import data.Articulo;
import data.Cliente;
import data.Ejemplar;
import data.Gerente;
import data.PersonalTienda;
import data.Tienda;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import static data.Ejemplar.getContIdGlobalEjemplares;
import data.Venta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author grovy
 */
public class PanelAgregarVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuGerente
     */
    private VentanaPrincipal v;
    private Tienda t;
    private PersonalTienda pt;
    private List<Articulo> copiaArticulos;
    private Cliente clienteElegido;
    private List<Ejemplar> carrito= new ArrayList<>();
    
    
    public PanelAgregarVenta(VentanaPrincipal v, Tienda t, PersonalTienda pt, Cliente clienteElegido) {
        this.t=t;
        this.v=v;
        this.pt=pt;
        this.clienteElegido=clienteElegido;
        this.copiaArticulos=t.getArticulosTienda();
        //v.setSize(600, 600);
        //v.setLocationRelativeTo(null);
        
        
        initComponents();
        
        nombreGerente.setText("Bienvenido a "+ t.getNombre()+", "+pt.getNombreCompleto());
        
        
        //por algun motivo no me funcionaba usando un split como en articulos
        //o en dependientes, asique he tenido que idear esto
    
        actualizarListaEjemplares();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        bAgregarCarrito = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCarrito = new javax.swing.JTextArea();
        bCrearVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nombreGerente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bVolverAtras = new javax.swing.JButton();
        bVolverMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 5));
        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(0, 10));

        lista.setBackground(new java.awt.Color(0, 51, 51));
        lista.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        lista.setForeground(new java.awt.Color(255, 255, 255));
        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lista);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        bAgregarCarrito.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        bAgregarCarrito.setText("Agregar al carrito");
        bAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarCarritoActionPerformed(evt);
            }
        });
        jPanel6.add(bAgregarCarrito, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(0, 10));

        tCarrito.setEditable(false);
        tCarrito.setBackground(new java.awt.Color(0, 51, 51));
        tCarrito.setColumns(18);
        tCarrito.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        tCarrito.setForeground(new java.awt.Color(255, 255, 255));
        tCarrito.setRows(5);
        jScrollPane1.setViewportView(tCarrito);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        bCrearVenta.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        bCrearVenta.setText("Crear Venta");
        bCrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearVentaActionPerformed(evt);
            }
        });
        jPanel7.add(bCrearVenta, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        nombreGerente.setFont(new java.awt.Font("FOT-Cezanne Pro B", 1, 18)); // NOI18N
        nombreGerente.setForeground(new java.awt.Color(255, 255, 255));
        nombreGerente.setText("Bienvenido \"Nombre Empleado\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 119, 29, 95);
        jPanel2.add(nombreGerente, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);

        bVolverAtras.setText("  Volver atras  ");
        bVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverAtrasActionPerformed(evt);
            }
        });
        jPanel4.add(bVolverAtras);

        bVolverMenu.setText("Volver al menu");
        bVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverMenuActionPerformed(evt);
            }
        });
        jPanel4.add(bVolverMenu);

        add(jPanel4, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarCarritoActionPerformed
       
        //si no seleccionas ningun elemento te salta el mensaje y no ejecuta el resto del codigo
        if(lista.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Debes elegir un elemento de la lista");
            return;
        }
        
        int indiceSeleccionado = lista.getSelectedIndex(); 
       

        if (indiceSeleccionado != -1) { //esto es para verificar que se ha seleccionado un elemento
            int cont = 0;
            for (int i = 0; i < this.copiaArticulos.size(); i++) {
                Articulo articulo = this.copiaArticulos.get(i);
                for (int j = 0; j < articulo.getEjemplaresArticulo().size(); j++) {
                    if (cont == indiceSeleccionado) { 
                        //si el contador coincide con lo seleccionado, lo borra de la copia de mis articulos y de la lista
                        tCarrito.append(articulo.getEjemplaresArticulo().get(j).toString()+"\n");
                        carrito.add(articulo.getEjemplaresArticulo().get(j));
                        articulo.getEjemplaresArticulo().remove(j);
                        articulo.disminuirCantidadEjemplares();
                        actualizarListaEjemplares();
                        return; //esto es para que deje de buscar
                    }
                    cont++;
                }
            }
        }
    }//GEN-LAST:event_bAgregarCarritoActionPerformed

    private void bCrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearVentaActionPerformed
        // Reemplaza los articulos de la tienda por la copia de articulos en la que ya se han borrado
        
        
        t.setArticulosTienda(this.copiaArticulos);
        clienteElegido.getVentasCliente().add(new Venta(carrito,clienteElegido));
        JOptionPane.showMessageDialog(this, " La venta ha sido realizada con exito ");
        this.v.ponPanelVentas(Paneles.PGestionarVentas, pt, clienteElegido);

    }//GEN-LAST:event_bCrearVentaActionPerformed

    private void bVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverMenuActionPerformed
        // TODO add your handling code here:
        //esto vuelve al menu principal
        if(pt.getClass()==Gerente.class)
        this.v.ponPanel(Paneles.PMenuGerente, pt);
        else
        this.v.ponPanel(Paneles.PMenuDependiente, pt);
    }//GEN-LAST:event_bVolverMenuActionPerformed

    private void bVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverAtrasActionPerformed
        // TODO add your handling code here:
        
        this.v.ponPanel(Paneles.PGestionarVentas, pt);
    }//GEN-LAST:event_bVolverAtrasActionPerformed

    private void actualizarListaEjemplares() {
        String[] ejemplaresLista = generarListaEjemplares();
        lista.setListData(ejemplaresLista);
    }

    private String[] generarListaEjemplares() {
        
        int cont = 0;
        String[] ejemplaresLista = new String[getContIdGlobalEjemplares()]; 
        for (Articulo articulo : this.copiaArticulos) {
            for (Ejemplar ejemplar : articulo.getEjemplaresArticulo()) {
                ejemplaresLista[cont] = ejemplar.toString();
                cont++;}
        }
        // Devolver la lista de ejemplares
        return Arrays.copyOf(ejemplaresLista, cont); // Recortar el array al tamaño actualizado
    }
   
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        Image fondo = null;
        try {
            fondo = ImageIO.read(new File("src/IMG/fondoMenus.jpg")); //esto lo he tenido que buscar en internet
        } catch (IOException ex) {
            Logger.getLogger(PanelLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Image fondoEscalado = fondo.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
        
        g.drawImage(fondoEscalado, 0, 0, this);
        this.repaint();
        this.revalidate();
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarCarrito;
    private javax.swing.JButton bCrearVenta;
    private javax.swing.JButton bVolverAtras;
    private javax.swing.JButton bVolverMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lista;
    private javax.swing.JLabel nombreGerente;
    private javax.swing.JTextArea tCarrito;
    // End of variables declaration//GEN-END:variables
}
