//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Amigos.java
//  @ Date : 14/02/2024
//  @ Author : 
//
//



package Clase Juanito;


public class Amigos extends Compañeros de clase {
}
