//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Compañeros de clase.java
//  @ Date : 14/02/2024
//  @ Author : 
//
//



package Clase Juanito;


public abstract class Compañeros de clase {
	private Object Nombre;
	private Object EquipoDeBaloncestoFavo;
}
