package GUI;

import data.Juego;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Javier
 */
public class PJuego extends javax.swing.JPanel {

    
    Juego j;
    Image img;
    
    /**
     * Creates new form PJuego
     * @param j
     */
    public PJuego(Juego j) 
    {
        
        this.j=j;
        
    }
    
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        
        img=this.createImage(this.getWidth(),this.getHeight());        
        Graphics gg=img.getGraphics();
        
        gg.drawImage(j.bgImgMeta.getImage(), 0,0,this.getWidth(), this.getHeight(),this);
        
        gg.setColor(Color.white);
        gg.setFont(new Font("Arial",Font.BOLD,20));
        gg.drawString(""+this.j.getTiempo(),this.getWidth()/2 , 50);
        
        j.getMuñeco().dibujar(gg);
        j.getMeta().dibujar(gg);
        for(int i=0;i<j.getObstaculos().size();i++)
            j.getObstaculos().get(i).dibujar(gg);
        
        
        g.drawImage(img,0, 0, this.getWidth(),this.getHeight(),null);
       
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
