/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.util.List;

/**
 *
 * @author grovy
 */
public class PLab extends javax.swing.JPanel {

    /**
     * Creates new form PLab
     */
    Keko f;
    List<Figura> muros;
    
    public PLab(String lab, Keko f, List<Figura> muros) {
        initComponents();
        this.f=f;
        this.muros=muros;
        
        String lab2="<HTML><pre>";
        String[] split = lab.split("\n");
        
        for (String s : split) {
            lab2+=s+"<br>";
        }
        lab2+="</pre></HTML>";
        
        mapa.setText(lab2);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        
        this.f.Dibujar(g);
        
        for (Figura m : muros) {
            m.Dibujar(g);
        }
        this.repaint();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        mapa.setText("Aqui va el lab");
        jPanel3.add(mapa, new java.awt.GridBagConstraints());

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Laberinto DAM");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here  
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mapa;
    // End of variables declaration//GEN-END:variables
}
