package PanelesGUI;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 * Crea un panel capaz de recibir Strings de HTMLs y los pinta por pantalla
 * @author Nacho
 */
public class PanelPaginaDeTextoHTML extends javax.swing.JPanel {


    /**
     * Crea un panel Con un titulo y un cuadro de texto no editable
     * en el que se pondrá el texto recibido en formato HTML
     * @param titulo Titulo del panel
     * @param texto  Texto en HTML que quieres mostrar
     */
    public PanelPaginaDeTextoHTML(String titulo, String texto) {
        initComponents();
        modificarPanel(titulo, texto, null, false);
    }
    /**
     * Crea un panel Con un titulo y un cuadro de texto editable
     * en el que se pondrá el texto recibido en formato HTML
     * @param titulo Titulo del panel
     * @param texto  Texto en HTML que quieres mostrar
     * @param editable Si lo pones en true podras editar el texto
     */
    public PanelPaginaDeTextoHTML(String titulo, String texto, Boolean editable) {
        initComponents();
        modificarPanel(titulo, texto, null, editable);
    }
    /**
     * Crea un panel Con un titulo y un cuadro de texto editable
     * en el que se pondrá el texto recibido en formato HTML,
     * ademas puedes cambiar la fuente del titulo
     * @param titulo Titulo del panel
     * @param texto  Texto en HTML que quieres mostrar
     * @param editable Si lo pones en true podras editar el texto
     * @param fuenteTitulo Es la fuente que usará el titulo
     */
    public PanelPaginaDeTextoHTML(String titulo, String texto, Font fuenteTitulo, Boolean editable) {
        initComponents();
        modificarPanel(titulo, texto, fuenteTitulo, editable);
    }
    /**
     * Crea un panel Con un titulo y un cuadro de texto no editable
     * en el que se pondrá el texto recibido en formato HTML,
     * ademas puedes cambiar la fuente del titulo
     * @param titulo Titulo del panel
     * @param texto  Texto en HTML que quieres mostrar
     * @param fuenteTitulo Es la fuente que usará el titulo
     */
    public PanelPaginaDeTextoHTML(String titulo, String texto, Font fuenteTitulo) {
        initComponents();
        modificarPanel(titulo, texto, fuenteTitulo, false);
    }
    
    private void modificarPanel(String titulo, String texto, Font fuenteTitulo, Boolean editable){
        
        cuadroTexto.setContentType("text/html");
        
        if (titulo!=null)
            this.titulo.setText(titulo);
        
        if (texto!=null)
            this.cuadroTexto.setText(texto);
        
        this.cuadroTexto.setEditable(editable);
        
        if (fuenteTitulo!=null)
            this.titulo.setFont(fuenteTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroTexto = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(54, 54, 54));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setText("Titulo");
        jPanel1.add(titulo);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(cuadroTexto);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cuadroTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public JTextPane getCuadroTexto() {
        return cuadroTexto;
    }

    public JLabel getTitulo() {
        return titulo;
    }
    
    
}
